Add all-tests-passed

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -252,3 +252,29 @@ jobs:
           src: >-
             __tests__/fixtures/python-project/src/python_project/__init__.py
             __tests__/fixtures/python-project/src/python_project/hello_world.py
+
+  all-tests-passed:
+    runs-on: ubuntu-latest
+    needs:
+      - lint
+      - test-latest-version
+      - test-specific-version
+      - test-version-from-version-file-pyproject
+      - test-default-version-from-pyproject
+      - test-default-version-from-pyproject-dev-group
+      - test-default-version-from-pyproject-dependency-groups
+      - test-default-version-from-pyproject-optional-dependencies
+      - test-default-version-from-requirements
+      - test-semver-range
+      - test-checksum
+      - test-with-explicit-token
+      - test-args
+      - test-failure
+      - test-multiple-src
+    if: always()
+    steps:
+      - name: All tests passed
+        run: |
+          echo "All jobs passed: ${{ !contains(needs.*.result, 'failure') }}"
+          # shellcheck disable=SC2242
+          exit ${{ contains(needs.*.result, 'failure') && 1 || 0 }}
